export const KEY_ESC = 'Escape';
export const KEY_ENTER = 'Enter';
// {
//   BACKSPACE: 'Backspace',
//   TAB: 'Tab',
//   ENTER: 'Enter',
//   SHIFT: 'Shift',
//   CONTROL: 'Ctrl',
//   ALT: 'Alt',
//   PAUSE: 'Pause',
//   CAPS_LOCK: 'CapsLock',
//   ESCAPE: 'Escape',
//   SPACE: ' ',
//   PAGE_UP: 'PageUp',
//   PAGE_DOWN: 'PageDown',
//   END: 'End',
//   HOME: 'Home',
//   ARROW_LEFT: 'ArrowLeft',
//   ARROW_UP: 'ArrowUp',
//   ARROW_RIGHT: 'ArrowRight',
//   ARROW_DOWN: 'ArrowDown',
//   INSERT: 'Insert',
//   DELETE: 'Delete',
//   META: 'Meta',
//   CONTEXTMENU: 'ContextMenu',
//   F1: 'F1',
//   F2: 'F2',
//   F3: 'F3',
//   F4: 'F4',
//   F5: 'F5',
//   F6: 'F6',
//   F7: 'F7',
//   F8: 'F8',
//   F9: 'F9',
//   F10: 'F10',
//   F11: 'F11',
//   F12: 'F12',
//   NUM_LOCK: 'NumLock',
//   SCROLL_LOCK: 'ScrollLock',
//   SEMICOLON: ';',
//   EQUAL: '=',
//   COMMA: ',',
//   MINUS: '-',
//   PERIOD: '.',
//   SLASH: '/',
//   BACK_QUOTE: '`',
//   BRACKET_LEFT: '[',
//   BACKSLASH: '\\',
//   QUOTE: "'",
// };
